### ISSUE TITLE
undefined method `keys' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by cdadar** [marguerite/diagnose#1]
pkmswitch100 脚本在 `openSUSE Leap 15.1`执行报错了
```./pkmswitch100/pkmswitch100.rb:113:in `block in <main>': undefined method `keys' for nil:NilClass (NoMethodError)```

是这个包没有 v['v']  导致的
`"cmus-plugin-ffmpeg"=>{"i"=>{"2.8.0~20180422.gb595b8c-lp151.2.3"=>["x86_64"]}}`

**Comment by marguerite** [comment]
please try the latest golang-version pkmswitch100. I place the binary on github so you can just download and run
